export const ROUTES = {
  login: "/login",
  dashboard: "/",
  categories: "/categories",
  products: "/products",
} as const;

export const TEST_IDS = {
  auth: {
    username: "auth-username-input",
    password: "auth-password-input",
    submit: "auth-submit-btn",
  },
  categories: {
    openAddModal: "category-open-btn",
    openEditModal: "category-edit-btn",
    deleteBtn: "category-delete-btn",
    viewBtn: "category-view-btn",
    title: "category-title-input",
    uploadImage: "category-image-upload-btn",
    uploadImageInput: "category-image-upload-input",
    submit: "category-submit-btn",
    categoryItem: "category-item",
    categoryName: "category-name",
  },
  products: {
    createBtn: "product-create-btn",
    editBtn: "product-edit-btn",
    deleteBtn: "product-delete-btn",
    title: "product-title-input",
    imageAlt: "product-image-alt-input",
    price: "product-price-input",
    category: "product-category-select",
    categoryOptionPrefix: "product-category-option",
    subCategory: "product-subcategory-select",
    subCategoryOptionPrefix: "product-subcategory-option",
    onSale: "product-on-sale-switch",
    salePrice: "product-sale-price-input",
    uploadImage: "product-image-upload-btn",
    uploadImageInput: "product-image-upload-input",
    submit: "product-submit-btn",
    productItem: "product-item",
    productName: "product-name",
    addComponentBtn: "product-add-component-btn",
    componentsSubmit: "product-components-submit-btn",
    componentNameInput: "component-name-input",
    componentImageAltInput: "component-image-alt-input",
    componentImageUploadBtn: "component-image-upload-btn",
    componentImageUploadInput: "component-image-upload-input",
    componentDeleteBtn: "component-delete-btn",
    addOptionGroupBtn: "product-add-option-group-btn",
    optionsSubmit: "product-options-submit-btn",
    optionGroupNameInput: "option-group-name-input",
    optionGroupTypeSelect: "option-group-type-select",
    optionGroupDeleteBtn: "option-group-delete-btn",
    optionValueLabelInput: "option-value-label-input",
    optionValueExtraPriceInput: "option-value-extra-price-input",
    optionValueDeleteBtn: "option-value-delete-btn",
    optionGroupAddValueBtn: "option-group-add-value-btn",
    tabBase: "product-tab-base",
    tabComponents: "product-tab-components",
    tabOptions: "product-tab-options",
    tabpanelBase: "product-tabpanel-base",
    tabpanelComponents: "product-tabpanel-components",
    tabpanelOptions: "product-tabpanel-options",
  },
  snackbar: "snackbar-alert",
  confirmYesBtn: "confirm-yes-btn",
  confirmNoBtn: "confirm-no-btn",
} as const;
